// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RessourceRelationnel.Infrastructure.Data;

#nullable disable

namespace RessourceRelationnel.Infrastructure.Data.Migrations
{
    [DbContext(typeof(RRDbContext))]
    [Migration("20260213141344_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RessourceRelationnel.Domain.Models.Categorie", b =>
                {
                    b.Property<long>("IdCategorie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("NomCategorie")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nom_categorie");

                    b.HasKey("IdCategorie");

                    b.ToTable("categorie", (string)null);
                });

            modelBuilder.Entity("RessourceRelationnel.Domain.Models.Message", b =>
                {
                    b.Property<long>("IdMessage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("contenu");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_creation");

                    b.Property<long>("IdUtilisateur")
                        .HasColumnType("bigint")
                        .HasColumnName("id_utilisateur");

                    b.HasKey("IdMessage");

                    b.HasIndex("IdUtilisateur");

                    b.ToTable("Message", (string)null);
                });

            modelBuilder.Entity("RessourceRelationnel.Domain.Models.Progression", b =>
                {
                    b.Property<long>("IdProgression")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("IdUtilisateur")
                        .HasColumnType("bigint")
                        .HasColumnName("id_utilisateur");

                    b.Property<string>("Valeur")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("progression");

                    b.HasKey("IdProgression");

                    b.HasIndex("IdUtilisateur");

                    b.ToTable("progression", (string)null);
                });

            modelBuilder.Entity("RessourceRelationnel.Domain.Models.Ressource", b =>
                {
                    b.Property<long>("IdRessource")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("format");

                    b.Property<long>("IdCategorie")
                        .HasColumnType("bigint")
                        .HasColumnName("id_categorie");

                    b.Property<long>("IdUtilisateur")
                        .HasColumnType("bigint")
                        .HasColumnName("id_utilisateur");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("titre");

                    b.HasKey("IdRessource");

                    b.HasIndex("IdCategorie");

                    b.HasIndex("IdUtilisateur");

                    b.ToTable("Ressource", (string)null);
                });

            modelBuilder.Entity("RessourceRelationnel.Domain.Models.Role", b =>
                {
                    b.Property<long>("IdRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("NomRole")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nom_role");

                    b.HasKey("IdRole");

                    b.ToTable("role", (string)null);
                });

            modelBuilder.Entity("RessourceRelationnel.Domain.Models.Statistique", b =>
                {
                    b.Property<long>("IdStatistique")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("IdUtilisateur")
                        .HasColumnType("bigint")
                        .HasColumnName("id_utilisateur");

                    b.Property<string>("Valeur")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("statistique");

                    b.HasKey("IdStatistique");

                    b.HasIndex("IdUtilisateur");

                    b.ToTable("Statistique", (string)null);
                });

            modelBuilder.Entity("RessourceRelationnel.Domain.Models.Utilisateur", b =>
                {
                    b.Property<long>("IdUtilisateur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<long>("IdRole")
                        .HasColumnType("bigint")
                        .HasColumnName("id_role");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nom");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("prenom");

                    b.HasKey("IdUtilisateur");

                    b.HasIndex("IdRole");

                    b.ToTable("Utilisateur", (string)null);
                });

            modelBuilder.Entity("RessourceRelationnel.Domain.Models.Message", b =>
                {
                    b.HasOne("RessourceRelationnel.Domain.Models.Utilisateur", "Utilisateur")
                        .WithMany("Messages")
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("RessourceRelationnel.Domain.Models.Progression", b =>
                {
                    b.HasOne("RessourceRelationnel.Domain.Models.Utilisateur", "Utilisateur")
                        .WithMany("Progressions")
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("RessourceRelationnel.Domain.Models.Ressource", b =>
                {
                    b.HasOne("RessourceRelationnel.Domain.Models.Categorie", "Categorie")
                        .WithMany("Ressources")
                        .HasForeignKey("IdCategorie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RessourceRelationnel.Domain.Models.Utilisateur", "Utilisateur")
                        .WithMany("Ressources")
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categorie");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("RessourceRelationnel.Domain.Models.Statistique", b =>
                {
                    b.HasOne("RessourceRelationnel.Domain.Models.Utilisateur", "Utilisateur")
                        .WithMany("Statistiques")
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("RessourceRelationnel.Domain.Models.Utilisateur", b =>
                {
                    b.HasOne("RessourceRelationnel.Domain.Models.Role", "Role")
                        .WithMany("Utilisateurs")
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("RessourceRelationnel.Domain.Models.Categorie", b =>
                {
                    b.Navigation("Ressources");
                });

            modelBuilder.Entity("RessourceRelationnel.Domain.Models.Role", b =>
                {
                    b.Navigation("Utilisateurs");
                });

            modelBuilder.Entity("RessourceRelationnel.Domain.Models.Utilisateur", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Progressions");

                    b.Navigation("Ressources");

                    b.Navigation("Statistiques");
                });
#pragma warning restore 612, 618
        }
    }
}
