// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RessourceRelationnel.Infrastructure.Data;

#nullable disable

namespace RessourceRelationnel.Infrastructure.Data.Migrations
{
    [DbContext(typeof(RRDbContext))]
    partial class RRDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RessourceRelationnel.Domain.Models.Categorie", b =>
                {
                    b.Property<long>("IdCategorie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("NomCategorie")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nom_categorie");

                    b.HasKey("IdCategorie");

                    b.ToTable("categorie", (string)null);
                });

            modelBuilder.Entity("RessourceRelationnel.Domain.Models.Commentaire", b =>
                {
                    b.Property<long>("IdCommentaire")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("contenu");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_creation");

                    b.Property<long?>("IdCommentaireParent")
                        .HasColumnType("bigint")
                        .HasColumnName("id_commentaire_parent");

                    b.Property<long>("IdRessource")
                        .HasColumnType("bigint")
                        .HasColumnName("id_ressource");

                    b.Property<long>("IdUtilisateur")
                        .HasColumnType("bigint")
                        .HasColumnName("id_utilisateur");

                    b.HasKey("IdCommentaire");

                    b.HasIndex("IdCommentaireParent");

                    b.HasIndex("IdRessource");

                    b.HasIndex("IdUtilisateur");

                    b.ToTable("commentaire", (string)null);
                });

            modelBuilder.Entity("RessourceRelationnel.Domain.Models.Favori", b =>
                {
                    b.Property<long>("IdUtilisateur")
                        .HasColumnType("bigint");

                    b.Property<long>("IdRessource")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateAjout")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_ajout");

                    b.HasKey("IdUtilisateur", "IdRessource");

                    b.HasIndex("IdRessource");

                    b.ToTable("favori", (string)null);
                });

            modelBuilder.Entity("RessourceRelationnel.Domain.Models.Message", b =>
                {
                    b.Property<long>("IdMessage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("contenu");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_creation");

                    b.Property<long?>("IdDestinataire")
                        .HasColumnType("bigint")
                        .HasColumnName("id_destinataire");

                    b.Property<long?>("IdRessource")
                        .HasColumnType("bigint")
                        .HasColumnName("id_ressource");

                    b.Property<long>("IdUtilisateur")
                        .HasColumnType("bigint")
                        .HasColumnName("id_utilisateur");

                    b.Property<string>("StatutInvitation")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("statut_invitation");

                    b.Property<string>("TypeMessage")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("type_message");

                    b.HasKey("IdMessage");

                    b.HasIndex("IdDestinataire");

                    b.HasIndex("IdRessource");

                    b.HasIndex("IdUtilisateur");

                    b.ToTable("Message", (string)null);
                });

            modelBuilder.Entity("RessourceRelationnel.Domain.Models.Progression", b =>
                {
                    b.Property<long>("IdProgression")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("IdUtilisateur")
                        .HasColumnType("bigint")
                        .HasColumnName("id_utilisateur");

                    b.Property<string>("Valeur")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("progression");

                    b.HasKey("IdProgression");

                    b.HasIndex("IdUtilisateur");

                    b.ToTable("progression", (string)null);
                });

            modelBuilder.Entity("RessourceRelationnel.Domain.Models.Ressource", b =>
                {
                    b.Property<long>("IdRessource")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_creation");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("format");

                    b.Property<long>("IdCategorie")
                        .HasColumnType("bigint")
                        .HasColumnName("id_categorie");

                    b.Property<long>("IdUtilisateur")
                        .HasColumnType("bigint")
                        .HasColumnName("id_utilisateur");

                    b.Property<int>("Statut")
                        .HasColumnType("int")
                        .HasColumnName("statut");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("titre");

                    b.Property<int>("Visibilite")
                        .HasColumnType("int")
                        .HasColumnName("visibilite");

                    b.HasKey("IdRessource");

                    b.HasIndex("IdCategorie");

                    b.HasIndex("IdUtilisateur");

                    b.ToTable("Ressource", (string)null);
                });

            modelBuilder.Entity("RessourceRelationnel.Domain.Models.Role", b =>
                {
                    b.Property<long>("IdRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("NomRole")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nom_role");

                    b.HasKey("IdRole");

                    b.ToTable("role", (string)null);

                    b.HasData(
                        new
                        {
                            IdRole = 1L,
                            NomRole = "citoyen"
                        },
                        new
                        {
                            IdRole = 2L,
                            NomRole = "moderateur"
                        },
                        new
                        {
                            IdRole = 3L,
                            NomRole = "administrateur"
                        },
                        new
                        {
                            IdRole = 4L,
                            NomRole = "super_administrateur"
                        });
                });

            modelBuilder.Entity("RessourceRelationnel.Domain.Models.Statistique", b =>
                {
                    b.Property<long>("IdStatistique")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("IdUtilisateur")
                        .HasColumnType("bigint")
                        .HasColumnName("id_utilisateur");

                    b.Property<string>("Valeur")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("statistique");

                    b.HasKey("IdStatistique");

                    b.HasIndex("IdUtilisateur");

                    b.ToTable("Statistique", (string)null);
                });

            modelBuilder.Entity("RessourceRelationnel.Domain.Models.Utilisateur", b =>
                {
                    b.Property<long>("IdUtilisateur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<long>("IdRole")
                        .HasColumnType("bigint")
                        .HasColumnName("id_role");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsEmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_email_verified");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nom");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("prenom");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("IdUtilisateur");

                    b.HasIndex("IdRole");

                    b.ToTable("Utilisateur", (string)null);
                });

            modelBuilder.Entity("RessourceRelationnel.Domain.Models.Commentaire", b =>
                {
                    b.HasOne("RessourceRelationnel.Domain.Models.Commentaire", "ParentCommentaire")
                        .WithMany("Reponses")
                        .HasForeignKey("IdCommentaireParent")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RessourceRelationnel.Domain.Models.Ressource", "Ressource")
                        .WithMany("Commentaires")
                        .HasForeignKey("IdRessource")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RessourceRelationnel.Domain.Models.Utilisateur", "Utilisateur")
                        .WithMany("Commentaires")
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentCommentaire");

                    b.Navigation("Ressource");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("RessourceRelationnel.Domain.Models.Favori", b =>
                {
                    b.HasOne("RessourceRelationnel.Domain.Models.Ressource", "Ressource")
                        .WithMany("Favoris")
                        .HasForeignKey("IdRessource")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RessourceRelationnel.Domain.Models.Utilisateur", "Utilisateur")
                        .WithMany("Favoris")
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ressource");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("RessourceRelationnel.Domain.Models.Message", b =>
                {
                    b.HasOne("RessourceRelationnel.Domain.Models.Utilisateur", "Destinataire")
                        .WithMany("MessagesRecus")
                        .HasForeignKey("IdDestinataire")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RessourceRelationnel.Domain.Models.Ressource", "Ressource")
                        .WithMany("Messages")
                        .HasForeignKey("IdRessource")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RessourceRelationnel.Domain.Models.Utilisateur", "Auteur")
                        .WithMany("MessagesEmis")
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auteur");

                    b.Navigation("Destinataire");

                    b.Navigation("Ressource");
                });

            modelBuilder.Entity("RessourceRelationnel.Domain.Models.Progression", b =>
                {
                    b.HasOne("RessourceRelationnel.Domain.Models.Utilisateur", "Utilisateur")
                        .WithMany("Progressions")
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("RessourceRelationnel.Domain.Models.Ressource", b =>
                {
                    b.HasOne("RessourceRelationnel.Domain.Models.Categorie", "Categorie")
                        .WithMany("Ressources")
                        .HasForeignKey("IdCategorie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RessourceRelationnel.Domain.Models.Utilisateur", "Utilisateur")
                        .WithMany("Ressources")
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categorie");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("RessourceRelationnel.Domain.Models.Statistique", b =>
                {
                    b.HasOne("RessourceRelationnel.Domain.Models.Utilisateur", "Utilisateur")
                        .WithMany("Statistiques")
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("RessourceRelationnel.Domain.Models.Utilisateur", b =>
                {
                    b.HasOne("RessourceRelationnel.Domain.Models.Role", "Role")
                        .WithMany("Utilisateurs")
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("RessourceRelationnel.Domain.Models.Categorie", b =>
                {
                    b.Navigation("Ressources");
                });

            modelBuilder.Entity("RessourceRelationnel.Domain.Models.Commentaire", b =>
                {
                    b.Navigation("Reponses");
                });

            modelBuilder.Entity("RessourceRelationnel.Domain.Models.Ressource", b =>
                {
                    b.Navigation("Commentaires");

                    b.Navigation("Favoris");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("RessourceRelationnel.Domain.Models.Role", b =>
                {
                    b.Navigation("Utilisateurs");
                });

            modelBuilder.Entity("RessourceRelationnel.Domain.Models.Utilisateur", b =>
                {
                    b.Navigation("Commentaires");

                    b.Navigation("Favoris");

                    b.Navigation("MessagesEmis");

                    b.Navigation("MessagesRecus");

                    b.Navigation("Progressions");

                    b.Navigation("Ressources");

                    b.Navigation("Statistiques");
                });
#pragma warning restore 612, 618
        }
    }
}
